server:
  port: 18080

spring:
  main:
    banner-mode: "off"
  application:
    name: "file-consumer"
  flyway:
    enabled: true
    locations: classpath:db/migration/default
    baseline-on-migrate: true
    baseline-version: 1
  datasource:
    url: "jdbc:postgresql://localhost:5432/multi_tenant_db?currentSchema=public_sch"
    username: "tenantUser"
    password: "S3cret"
  jpa:
    database-platform: "org.hibernate.dialect.PostgreSQL95Dialect"

multi-tenant:
  tenants:
      - tenantId: Manipal_01
        enabled: true
        schema: manipal01
  kafka:
    bootstrap-servers: "localhost:29092"
    topic:
      tenant-topic: "tenant-topic1"
    tenant:
      consumer:
        group-id: "tenant-consumer"
  aws:
    s3:
      minio-url: "http://localhost:9000"
      access-key: "tenantUser"
      secret-key: "tenantPwd"
      region: "us-east-1"